language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
  - '4'
script:
  - npm test
  - npm run build
  - npm run build:umd
  - npm run build:min
after_success:
  - npm run semantic-release
branches:
  only:
    - master
